
const char* MAIN_page = "<!DOCTYPE html>"
"<html>"
"<style>"
".card{"
"max-width: 400px;"
"min-height: 500px;"
"background: #02b875;"
"padding: 30px;"
"box-sizing: border-box;"
"color: #FFF;"
"margin:20px;"
"box-shadow: 0px 2px 18px -4px rgba(0,0,0,0.75);"
"}"
"</style>"
"<body>"
"<div class=\"card\">"
"<h1>WuR Multiproto HTTP gateway </h4><br>"
"<button onclick=\"getWake()\">Wake Device</button><br>"
"<button onclick=\"getSleep()\">Sleep Device</button><br>"
"<button onclick=\"getData()\">Send Data</button><br>"
"<h4>Target Address:<input id=\"address\" value=\"0555\" type=\"string\"></h4><br>"
"<h4>Awake ms timeout:<input id=\"awake_ms\" value=\"1000\" type=\"number\"></h4><br>"
"<h4>Hex DATA:<input id=\"data\" value=\"05050505\" type=\"string\"></h4><br>"
"<h4>Message Status:<span id=\"message_status\">KO</span></h4><br>"
"<h4>Message_result:<span id=\"message_result\"></span></h4><br>"
"<button onclick=\"startTest()\">Start Test</button><br>"
"<h4>Test Status:<span id=\"test_status\">{}</span></41><br>"
"<h4>Process time:<span id=\"message_time\">0 ms</span></41><br>"
"</div>"
"<script>"
"var timestamp = 0;\n"
"var request_ongoing = false;\n"
"var test_ongoing = false;\n"
"setInterval(function() {\n"
"update_timers();\n"
"}, 100);\n"
"function getData() {\n"
"console.log(\"DATA device pressed\");\n"
"if(request_ongoing || test_ongoing){\n"
"console.log(\"DATA device canceled. Request ongoing\");\n"
"return;\n"
"}\n"
"var xhttp = new XMLHttpRequest();\n"
"xhttp.onreadystatechange = function() {\n"
"request_ongoing = false;\n"
"if (this.readyState == 4 && this.status == 200) {\n"
"document.getElementById(\"message_status\").innerHTML = \"OK\";\n"
"}else{\n"
"document.getElementById(\"message_status\").innerHTML = \"KO\";\n"
"}\n"
"document.getElementById(\"message_result\").innerHTML = this.response;\n"
"};\n"
"address = document.getElementById(\"address\").value;\n"
"data = document.getElementById(\"data\").value;\n"
"xhttp.open(\"POST\", \"wur/data\", true);\n"
"xhttp.setRequestHeader(\"Content-Type\", \"application/json;charset=UTF-8\");\n"
"xhttp.send(JSON.stringify({wur_address:address, data:data}));\n"
"request_ongoing = false;\n"
"timestamp = Date.now();\n"
"}\n"
"function getWake() {\n"
"console.log(\"WAKE device pressed\");\n"
"if(request_ongoing || test_ongoing){\n"
"console.log(\"WAKE device canceled. Request ongoing\");\n"
"return;\n"
"}\n"
"var xhttp = new XMLHttpRequest();\n"
"xhttp.onreadystatechange = function() {\n"
"request_ongoing = false;\n"
"if (this.readyState == 4 && this.status == 200) {\n"
"document.getElementById(\"message_status\").innerHTML = \"OK\";\n"
"}else{\n"
"document.getElementById(\"message_status\").innerHTML = \"KO\";\n"
"}\n"
"document.getElementById(\"message_result\").innerHTML = this.response;\n"
"};\n"
"address = document.getElementById(\"address\").value;\n"
"awake_time = parseInt(document.getElementById(\"awake_ms\").value);\n"
"xhttp.open(\"POST\", \"wur/wake\", true);\n"
"xhttp.setRequestHeader(\"Content-Type\", \"application/json;charset=UTF-8\");\n"
"xhttp.send(JSON.stringify({wur_address:address, wake_time:awake_time}));\n"
"request_ongoing = true;\n"
"timestamp = Date.now();\n"
"}\n"
"function getSleep() {\n"
"console.log(\"SLEEP device pressed\");\n"
"if(request_ongoing || test_ongoing){\n"
"console.log(\"SLEEP device canceled. Request ongoing\");\n"
"return;\n"
"}\n"
"var xhttp = new XMLHttpRequest();\n"
"xhttp.onreadystatechange = function() {\n"
"request_ongoing = false;\n"
"if (this.readyState == 4 && this.status == 200) {\n"
"document.getElementById(\"message_status\").innerHTML = \"OK\";\n"
"}else{\n"
"document.getElementById(\"message_status\").innerHTML = \"KO\";\n"
"}\n"
"document.getElementById(\"message_result\").innerHTML = this.response;\n"
"};\n"
"address = document.getElementById(\"address\").value;\n"
"awake_time = 0x0001;\n"
"xhttp.open(\"POST\", \"wur/wake\", true);\n"
"xhttp.setRequestHeader(\"Content-Type\", \"application/json;charset=UTF-8\");\n"
"xhttp.send(JSON.stringify({wur_address:address, wake_time:awake_time}));\n"
"request_ongoing = true;\n"
"timestamp = Date.now();\n"
"}\n"
"function startTest() {\n"
"console.log(\"TEST device pressed\");\n"
"if(request_ongoing || test_ongoing){\n"
"console.log(\"TEST device canceled. Request/test ongoing\");\n"
"return;\n"
"}\n"
"var xhttp = new XMLHttpRequest();\n"
"xhttp.onreadystatechange = function() {\n"
"if (this.readyState == 4 && this.status == 200) {\n"
"console.log(\"TEST device STARTED. Request/test ongoing\");\n"
"timestamp = Date.now();\n"
"test_ongoing = true;\n"
"}else if (this.readyState == 4 && this.status != 200){\n"
"console.log(\"TEST device NOT STARTED. Request/test finished\");\n"
"test_ongoing = false;\n"
"}\n"
"};\n"
"xhttp.open(\"POST\", \"wur/test/start\", true);\n"
"xhttp.setRequestHeader(\"Content-Type\", \"application/json;charset=UTF-8\");\n"
"xhttp.send(JSON.stringify({}));\n"
"}\n"
"function updateTestStatus() {\n"
"var xhttp = new XMLHttpRequest();\n"
"xhttp.onreadystatechange = function() {\n"
"if (this.readyState == 4 && this.status == 200) {\n"
"var jsonResponse = JSON.parse(this.responseText);\n"
"var result_string = jsonResponse.status + \"\\n\" + jsonResponse.currentFrame + \"/\" + jsonResponse.totalFrames;\n"
"console.log(\"TEST device status:\" + result_string);\n"
"document.getElementById(\"test_status\").innerHTML = result_string;\n"
"if(jsonResponse.status !== \"in_progress\"){test_ongoing = false;}\n" 
"}\n"
"};\n"
"xhttp.open(\"GET\", \"wur/test/status\", true);\n"
"xhttp.setRequestHeader(\"Content-Type\", \"application/json;charset=UTF-8\");\n"
"xhttp.send(JSON.stringify({}));\n"
"timestamp = Date.now();\n"
"}\n"
"function update_timers() {\n"
"if(request_ongoing){\n"
"var current_time = Date.now();\n"
"if(timestamp != 0){\n"
"document.getElementById(\"message_time\").innerHTML = current_time - timestamp;\n"
"}\n"
"}\n"
"if(test_ongoing){\n"
"var current_time = Date.now();\n"
"if(timestamp != 0){\n"
"time_delta = current_time - timestamp;\n"
"if(time_delta > 1000){\n"
"updateTestStatus()\n"
"}\n"
"}\n"
"}\n"
"}\n"
"</script>"
"</body>"
"</html>";