
const char* MAIN_page = "<!DOCTYPE html>"
"<html>"
"<style>"
".card{"
"max-width: 400px;"
"min-height: 500px;"
"background: #02b875;"
"padding: 30px;"
"box-sizing: border-box;"
"color: #FFF;"
"margin:20px;"
"box-shadow: 0px 2px 18px -4px rgba(0,0,0,0.75);"
"}"
"</style>"
"<body>"
"<div class=\"card\">"
"<h1>WuR Multiproto HTTP gateway </h4><br>"
"<button onclick=\"getWake()\">Wake Device</button><br>"
"<button onclick=\"getSleep()\">Sleep Device</button><br>"
"<button onclick=\"getData()\">Send Data</button><br>"
"<h4>Target Address:<input id=\"address\" value=\"0555\" type=\"string\"></h4><br>"
"<h4>Awake ms timeout:<input id=\"awake_ms\" value=\"1000\" type=\"number\"></h4><br>"
"<h4>Hex DATA:<input id=\"data\" value=\"05050505\" type=\"string\"></h4><br>"
"<h4>Message Status:<span id=\"message_status\">KO</span></h4><br>"
"<h4>Message_result:<span id=\"message_result\"></span></h4><br>"
"<h4>Message time:<span id=\"message_time\">0 ms</span></41><br>"
"</div>"
"<script>"
"var timestamp = 0;"
"var request_ongoing = false;"
"setInterval(function() {"
"update_timers();"
"}, 100);\n"
"function getData() {\n"
"console.log(\"DATA device pressed\");\n"
"if(request_ongoing){\n"
"console.log(\"DATA device canceled. Request ongoing\");\n"
"return;\n"
"}\n"
"var xhttp = new XMLHttpRequest();\n"
"xhttp.onreadystatechange = function() {\n"
"request_ongoing = false;\n"
"if (this.readyState == 4 && this.status == 200) {\n"
"document.getElementById(\"message_status\").innerHTML = \"OK\";\n"
"}else{\n"
"document.getElementById(\"message_status\").innerHTML = \"KO\";\n"
"}\n"
"document.getElementById(\"message_result\").innerHTML = this.response;\n"
"};\n"
"address = document.getElementById(\"address\").value;\n"
"data = document.getElementById(\"data\").value;\n"
"xhttp.open(\"POST\", \"wur/data\", true);\n"
"xhttp.setRequestHeader(\"Content-Type\", \"application/json;charset=UTF-8\");\n"
"xhttp.send(JSON.stringify({wur_address:address, data:data}));\n"
"request_ongoing = false;\n"
"timestamp = Date.now();\n"
"}\n"
"function getWake() {\n"
"console.log(\"WAKE device pressed\");\n"
"if(request_ongoing){\n"
"console.log(\"WAKE device canceled. Request ongoing\");\n"
"return;\n"
"}\n"
"var xhttp = new XMLHttpRequest();\n"
"xhttp.onreadystatechange = function() {\n"
"request_ongoing = false;\n"
"if (this.readyState == 4 && this.status == 200) {\n"
"document.getElementById(\"message_status\").innerHTML = \"OK\";\n"
"}else{\n"
"document.getElementById(\"message_status\").innerHTML = \"KO\";\n"
"}\n"
"document.getElementById(\"message_result\").innerHTML = this.response;\n"
"};\n"
"address = document.getElementById(\"address\").value;\n"
"awake_time = parseInt(document.getElementById(\"awake_ms\").value);\n"
"xhttp.open(\"POST\", \"wur/wake\", true);\n"
"xhttp.setRequestHeader(\"Content-Type\", \"application/json;charset=UTF-8\");\n"
"xhttp.send(JSON.stringify({wur_address:address, wake_time:awake_time}));\n"
"request_ongoing = true;\n"
"timestamp = Date.now();\n"
"}\n"
"function getSleep() {\n"
"console.log(\"SLEEP device pressed\");\n"
"if(request_ongoing){\n"
"console.log(\"SLEEP device canceled. Request ongoing\");\n"
"return;\n"
"}\n"
"var xhttp = new XMLHttpRequest();\n"
"xhttp.onreadystatechange = function() {\n"
"request_ongoing = false;\n"
"if (this.readyState == 4 && this.status == 200) {\n"
"document.getElementById(\"message_status\").innerHTML = \"OK\";\n"
"}else{\n"
"document.getElementById(\"message_status\").innerHTML = \"KO\";\n"
"}\n"
"document.getElementById(\"message_result\").innerHTML = this.response;\n"
"};\n"
"address = document.getElementById(\"address\").value;\n"
"awake_time = 0x0001;\n"
"xhttp.open(\"POST\", \"wur/wake\", true);\n"
"xhttp.setRequestHeader(\"Content-Type\", \"application/json;charset=UTF-8\");\n"
"xhttp.send(JSON.stringify({wur_address:address, wake_time:awake_time}));\n"
"request_ongoing = true;\n"
"timestamp = Date.now();\n"
"}\n"
"function update_timers() {"
"if(request_ongoing){"
"var current_time = Date.now();"
"if(timestamp != 0){"
"document.getElementById(\"message_time\").innerHTML = current_time - timestamp;"
"}"
"}"
"}"
"</script>"
"</body>"
"</html>";